### ISSUE TITLE
aplication isnt work 

### ISSUE THREAD

**Issue by shadow22000** [tzubertowski/mvf-interview-test#1]
1. https://github.com/tzubertowski/mvf-interview-test#1-building-the-app I`m not able to complete  first step of the set up 
2.
![image](https://user-images.githubusercontent.com/104870103/167463487-4cbee0c1-b852-49c2-8477-42dcc11f4635.png)
3.simple run ./run.sh dev

**Comment by tzubertowski** [comment]
Thanks for reporting. This has been fixed now with:
- https://github.com/tzubertowski/mvf-interview-test/commit/1621bffd2d37f4b5187cc3a325a0656f9cc8e583

Please retest @shadow22000 and let me know
